### ISSUE TITLE
Dataset Availabilty

### ISSUE THREAD

**Issue by saranggoel** [rachellea/ct-net-models#1]
Hello!

I thought this project was amazing! I was wondering if a dataset is available for the CT scans with all of the abnormalities. Tysm!

**Comment by rachellea** [comment]
Thank you for your interest! We are currently working on making the data
set public which requires going through the full university approval
process. Hopefully the data set will become public this coming spring.
Thank you,
Rachel

**Comment by ashim-nfer** [comment]
@rachellea Is this dataset available now? Would like to reproduce the results.

**Comment by rachellea** [comment]
Thank you for your interest. Unfortunately, the dataset is not available yet. Trust me, it has been an immense source of frustration that there is so much bureaucracy involved (on the order of 30+ people). I finished deidentifying and documenting the dataset many months ago but at this point the release process is out of my hands. There will be announcements once the data is released.
